# site settings
title: mecPortal
subtitle: A portal for model estimated controls
email: richj23@gmail.com
description: A portal to lean and use Model Estimated Controls
baseurl: /mecPortal # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Richard Jackson

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/richjjackson
  Twitter: https://twitter.com/richj23

# build settings
markdown: kramdown

sass:
  style: compressed

collections:
  models:
    output: true
  applications:
    output: true
  learn:
    output: true


exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
